version: '3'
services:
  web-02:
    image: apache
    container_name: $CONTAINER_NAME
    environment:
      VIRTUAL_HOST: $VIRTUAL_HOST
      LETSENCRYPT_HOST: $LETSENCRYPT_HOST
      LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL

networks:
  default:
    external:
      name: nginx-proxy
